version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: english_bot_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: english_bot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: english_bot
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - OPENAI_TOKEN=${OPENAI_TOKEN}
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/english_bot_db
      - DEBUG=${DEBUG:-false}
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env

volumes:
  postgres_data: